language: go
go:
- 1.7
- 1.8
- master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
branches:
  only:
  - master
install:
- go get github.com/urfave/cli
- go get github.com/stretchr/testify/assert
- go get github.com/sendgrid/rest
- go get github.com/gorilla/websocket
